### ISSUE TITLE
Illegal Unicode Following `"` or `'` Causes `lua_parser::parse_str` Panic

### ISSUE THREAD

**Issue by rfuzz** [ehwan/lua_rust#3]
Hello, I have found another input that causes the `lua_parser::parse_str` function to panic. An illegal Unicode character like `\u{11FFFF}` that follows `"` or `'` will trigger a panic.

```rust
use lua_parser::parse_str;

fn main() {
    let source = r#"'\u{11FFFF}"#;
    let block = match lua_parser::parse_str(&source) {
        Ok(block) => block,
        Err(err) => {
            println!("ERR");
            return;
        }
    };
    println!("AST:\n{:#?}", block);
}
```

After running the code, the following panic occurs:

```shell
thread 'main' panicked at /home/ubuntu/lua_rust/tokenizer/src/lib.rs:637:79:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/panicking.rs:148:5
   3: core::option::unwrap_failed
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/option.rs:2004:5
   4: core::option::Option<T>::unwrap
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/option.rs:969:21
   5: lua_tokenizer::Tokenizer::short_string_literal
             at /home/ubuntu/lua_rust/tokenizer/src/lib.rs:637:41
   6: lua_tokenizer::Tokenizer::tokenize_string
             at /home/ubuntu/lua_rust/tokenizer/src/lib.rs:751:25
   7: lua_tokenizer::Tokenizer::tokenize_literal
             at /home/ubuntu/lua_rust/tokenizer/src/lib.rs:171:37
   8: lua_tokenizer::Tokenizer::try_tokenize
             at /home/ubuntu/lua_rust/tokenizer/src/lib.rs:831:37
   9: <lua_tokenizer::Tokenizer as core::iter::traits::iterator::Iterator>::next
             at /home/ubuntu/lua_rust/tokenizer/src/lib.rs:1109:15
  10: lua_parser::parse_str
             at /home/ubuntu/lua_rust/parser/src/lib.rs:90:18
  11: lua_rust_fuzz_target_test::main
             at ./src/main.rs:5:23
  12: core::ops::function::FnOnce::call_once
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

version: `commit d7979a1f61245ef89ef7ef8ffe6fba424f86e9a1`

**Comment by ehwan** [comment]
Thank you @rfuzz!
I should have added more tests :)
